import pygame
import numpy as np

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 1024

THRUST = 0.01
PI = np.pi
DEG_TO_RAD = PI / 180.0

BULLET_SPAWN_RADIUS = 32/1024

FIRE_COOLDOWN = 200
FIRE_LIFETIME = 1000
FIRE_SPEED = 30

# Events
SHIP_SPAWN_EVENT = pygame.USEREVENT + 1
FIRE_EVENT = pygame.USEREVENT + 2
FIRE_DIE_EVENT = pygame.USEREVENT + 3
EXPLODE_DEBRIS = pygame.USEREVENT + 4


# Audio
FADE_OUT_TIME = 200
UI_CHANNEL = 0
THRUST_CHANNEL = 1
LASER_CHANNEL = 2
EXPLOSION_CHANNEL = 3
UFO_CHANNEL = 4
